

vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/dspba_library_package.vhd"                      
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/dspba_library.vhd"                              
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlogan +v2k  "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/altera_avalon_sc_fifo.v"                        
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_rtl_core.vhd"                               
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_ast.vhd"                                    
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir.vhd"                                        
vhdlan -xlrm "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_tb.vhd"                                     
