

vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/dspba_library_package.vhd"                      
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/dspba_library.vhd"                              
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_math_pkg_hpfir.vhd"                   
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_lib_pkg_hpfir.vhd"                    
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_controller_hpfir.vhd"
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_sink_hpfir.vhd"      
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_avalon_streaming_source_hpfir.vhd"    
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/auk_dspip_roundsat_hpfir.vhd"                   
vlog "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/altera_avalon_sc_fifo.v"                        
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_rtl_core.vhd"                               
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_ast.vhd"                                    
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir.vhd"                                        
vcom "C:/Users/Administrator/Desktop/QamCarrierDD/fir_sim/fir_tb.vhd"                                     
